version: '3.8'

networks:
  openvpn:
    name: openvpn
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.192.0/20
          gateway: 192.168.192.1
  research_network:
    name: research_network

volumes:
  research-data:
    name: research-data
  uploads:
    name: research_uploads
  storage-uploads:
    name: research_storage-uploads

services:
  openvpn:
    container_name: openvpn_server
    image: kylemanna/openvpn
    cap_add:
     - NET_ADMIN
    ports:
     - "1194:1194/udp"
    volumes:
     - ./Conteiner/openVpn/openvpn-data:/etc/openvpn
     - ./Conteiner/openVpn/bin:/usr/local/bin
    dns:
      - 1.1.1.1
    networks:
      openvpn:
        ipv4_address: 192.168.192.2

  mysql:
    container_name: research_DB
    image: mysql:8.0
    depends_on:
      - openvpn
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=secret
    volumes:
      - research-data:/var/lib/mysql
    networks:
      - research_network

  bookstack:
    container_name: research
    image: solidnerd/bookstack:22.10.2
    depends_on:
      - mysql
      - openvpn
    restart: always
    environment:
      - DB_HOST=research_DB
      - DB_DATABASE=bookstack
      - DB_USERNAME=bookstack
      - DB_PASSWORD=secret
      - APP_URL=http://192.168.255.1:8080
    volumes:
      - uploads:/var/www/bookstack/public/uploads
      - storage-uploads:/var/www/bookstack/storage/uploads
    networks:
      research_network:
      openvpn:
        ipv4_address: 192.168.192.3

  phpmyadminapione:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST:  research_DB
      PMA_PORT: 3306
    depends_on:
      - mysql
      - openvpn
    networks:
      research_network:
      openvpn:
        ipv4_address: 192.168.192.4